-- HunterFit — Seed: catálogo de ejercicios (~80)
-- difficulty: 1=principiante, 2=intermedio, 3=avanzado, 4=élite
insert into exercises (slug, name_es, category, muscle_groups, equipment, difficulty, instructions_es, default_sets, default_reps, default_seconds, rest_seconds, met_value) values

-- ===== FUERZA: EMPUJE =====
('pushup_knees','Lagartijas con rodillas','strength','{pecho,brazos,core}','ninguno',1,'Apoya rodillas y manos al ancho de hombros. Baja el pecho controlado y empuja. Mantén el core firme.',3,10,null,60,3.8),
('pushup','Lagartijas','strength','{pecho,brazos,core}','ninguno',2,'Cuerpo en línea recta, manos al ancho de hombros. Baja hasta casi tocar el suelo y empuja con fuerza.',3,12,null,60,4.0),
('pushup_diamond','Lagartijas diamante','strength','{brazos,pecho}','ninguno',3,'Manos juntas formando un diamante bajo el pecho. Codos pegados al torso al bajar.',3,10,null,75,4.5),
('pushup_archer','Lagartijas arquero','strength','{pecho,brazos,core}','ninguno',4,'Manos muy abiertas; baja cargando el peso hacia un brazo mientras el otro se estira. Alterna lados.',3,8,null,90,5.0),
('pike_pushup','Lagartijas pica','strength','{hombros,brazos}','ninguno',2,'Cadera elevada en V invertida. Baja la cabeza hacia el suelo flexionando codos y empuja.',3,10,null,75,4.2),
('bench_press','Press de banca','strength','{pecho,brazos,hombros}','barra',2,'Acostado en banco, baja la barra al pecho con control y empuja hasta extender los brazos.',4,8,null,90,5.0),
('db_press','Press con mancuernas','strength','{pecho,brazos}','mancuernas',2,'Acostado, empuja las mancuernas desde el pecho hasta arriba. Baja lento.',4,10,null,90,5.0),
('shoulder_press','Press militar','strength','{hombros,brazos}','mancuernas',2,'De pie o sentado, empuja las mancuernas desde los hombros hasta arriba sin arquear la espalda.',4,10,null,90,5.0),
('lateral_raise','Elevaciones laterales','strength','{hombros}','mancuernas',1,'Brazos casi rectos, eleva las mancuernas a los lados hasta la altura de hombros. Baja lento.',3,12,null,60,3.5),
('dips_bench','Fondos en banco','strength','{brazos,pecho}','ninguno',1,'Manos en el borde de un banco o silla, baja flexionando codos a 90° y empuja.',3,12,null,60,4.0),
('dips','Fondos en paralelas','strength','{pecho,brazos}','ninguno',3,'En paralelas, baja controlado hasta 90° de codo y empuja. Inclínate adelante para más pecho.',3,10,null,90,5.5),

-- ===== FUERZA: TRACCIÓN =====
('row_db','Remo con mancuerna','strength','{espalda,brazos}','mancuernas',1,'Apoya una mano en banco, espalda recta. Jala la mancuerna hacia la cadera y baja lento.',4,10,null,75,4.5),
('row_inverted','Remo invertido','strength','{espalda,brazos,core}','ninguno',2,'Cuélgate bajo una mesa o barra baja, cuerpo recto. Jala el pecho hacia la barra.',3,10,null,75,4.5),
('pullup_assisted','Dominadas asistidas','strength','{espalda,brazos}','banda',2,'Con banda elástica en los pies, jala hasta pasar la barbilla sobre la barra. Baja controlado.',3,8,null,90,5.0),
('pullup','Dominadas','strength','{espalda,brazos,core}','ninguno',3,'Cuelga de la barra con agarre prono. Jala hasta pasar la barbilla y baja lento sin balancearte.',4,8,null,90,5.5),
('chinup','Dominadas supinas','strength','{brazos,espalda}','ninguno',3,'Agarre con palmas hacia ti. Jala con bíceps y espalda hasta pasar la barbilla.',3,8,null,90,5.5),
('curl_db','Curl de bíceps','strength','{brazos}','mancuernas',1,'De pie, codos pegados al torso. Sube las mancuernas girando las muñecas y baja lento.',3,12,null,60,3.5),
('facepull_band','Jalón a la cara con banda','strength','{hombros,espalda}','banda',1,'Jala la banda hacia tu cara separando las manos al final. Aprieta omóplatos.',3,15,null,60,3.0),
('superman','Superman','strength','{espalda,gluteos}','ninguno',1,'Boca abajo, eleva brazos y piernas a la vez. Sostén 2 segundos arriba y baja.',3,12,null,45,3.0),

-- ===== FUERZA: PIERNAS Y GLÚTEOS =====
('squat_air','Sentadillas','strength','{piernas,gluteos}','ninguno',1,'Pies al ancho de hombros, baja como si te sentaras hasta muslos paralelos. Pecho arriba.',3,15,null,60,4.0),
('squat_goblet','Sentadilla goblet','strength','{piernas,gluteos,core}','mancuernas',2,'Sostén una mancuerna al pecho. Baja profundo manteniendo la espalda recta.',4,12,null,75,5.0),
('squat_barbell','Sentadilla con barra','strength','{piernas,gluteos,core}','barra',3,'Barra sobre trapecios. Baja controlado hasta paralelo y empuja con fuerza desde los talones.',4,8,null,120,6.0),
('squat_jump','Sentadilla con salto','strength','{piernas,gluteos}','ninguno',2,'Baja a sentadilla y explota hacia arriba en un salto. Aterriza suave y repite.',3,12,null,75,7.0),
('squat_pistol','Sentadilla pistola','strength','{piernas,gluteos,core}','ninguno',4,'Sentadilla a una pierna con la otra extendida al frente. Usa apoyo si lo necesitas.',3,6,null,90,6.0),
('lunge','Desplantes','strength','{piernas,gluteos}','ninguno',1,'Da un paso largo al frente y baja la rodilla trasera casi al suelo. Alterna piernas.',3,12,null,60,4.5),
('lunge_walking','Desplantes caminando','strength','{piernas,gluteos}','mancuernas',2,'Desplantes avanzando con mancuernas en mano. Torso erguido todo el tiempo.',3,20,null,75,5.5),
('bulgarian_split','Sentadilla búlgara','strength','{piernas,gluteos}','mancuernas',3,'Pie trasero elevado en banco. Baja vertical con la pierna delantera. Brutal pero efectiva.',3,10,null,90,6.0),
('deadlift_rdl','Peso muerto rumano','strength','{gluteos,piernas,espalda}','mancuernas',2,'Piernas casi rectas, baja las mancuernas pegadas a las piernas empujando la cadera atrás.',4,10,null,90,5.5),
('deadlift','Peso muerto','strength','{gluteos,piernas,espalda}','barra',3,'Espalda recta, levanta la barra del suelo extendiendo cadera y rodillas a la vez.',4,6,null,120,6.5),
('hip_thrust','Hip thrust','strength','{gluteos}','barra',2,'Espalda apoyada en banco, barra sobre la cadera. Empuja la cadera arriba apretando glúteos.',4,12,null,90,5.0),
('glute_bridge','Puente de glúteos','strength','{gluteos,core}','ninguno',1,'Acostado, rodillas flexionadas. Eleva la cadera apretando glúteos y sostén 2 segundos.',3,15,null,45,3.5),
('calf_raise','Elevación de talones','strength','{piernas}','ninguno',1,'De pie, sube a las puntas de los pies con control y baja lento. Agrega peso si es fácil.',3,20,null,45,3.0),
('step_up','Subidas a banco','strength','{piernas,gluteos}','ninguno',1,'Sube a un banco o escalón con una pierna, baja controlado. Alterna.',3,12,null,60,5.0),
('wall_sit','Sentadilla isométrica en pared','strength','{piernas}','ninguno',1,'Espalda contra la pared, muslos paralelos al suelo. Aguanta la posición.',3,null,40,60,3.5),

-- ===== FUERZA: CORE =====
('plank','Plancha','strength','{core}','ninguno',1,'Antebrazos en el suelo, cuerpo recto como tabla. No dejes caer la cadera.',3,null,30,45,3.0),
('plank_side','Plancha lateral','strength','{core}','ninguno',2,'De lado sobre un antebrazo, cuerpo en línea recta. Aguanta y cambia de lado.',3,null,30,45,3.0),
('crunch','Abdominales crunch','strength','{core}','ninguno',1,'Acostado, rodillas flexionadas. Eleva los omóplatos del suelo contrayendo el abdomen.',3,15,null,45,3.0),
('leg_raise','Elevación de piernas','strength','{core}','ninguno',2,'Acostado, piernas rectas. Súbelas a 90° y bájalas sin tocar el suelo.',3,12,null,60,3.5),
('russian_twist','Giros rusos','strength','{core}','ninguno',2,'Sentado con torso inclinado atrás, gira el torso de lado a lado. Peso opcional.',3,20,null,45,4.0),
('mountain_climber','Escaladores','strength','{core,piernas}','ninguno',2,'En posición de plancha alta, lleva las rodillas al pecho alternando rápido.',3,null,30,45,8.0),
('hollow_hold','Hollow hold','strength','{core}','ninguno',3,'Acostado, despega hombros y piernas del suelo formando un plátano. Aguanta.',3,null,25,60,3.5),
('dead_bug','Bicho muerto','strength','{core}','ninguno',1,'Boca arriba, brazos y rodillas a 90°. Extiende brazo y pierna contrarios sin arquear la espalda.',3,10,null,45,3.0),
('hanging_knee_raise','Elevación de rodillas colgado','strength','{core,brazos}','ninguno',3,'Colgado de la barra, sube las rodillas al pecho con control, sin balancearte.',3,10,null,75,4.0),
('lsit_tuck','L-sit tuck','strength','{core,brazos}','ninguno',4,'Apoyado en paralelas o suelo, despega el cuerpo y mantén las rodillas al pecho.',3,null,15,90,4.0),

-- ===== CARDIO =====
('jog_easy','Trote suave','cardio','{full_body}','ninguno',1,'Trota a ritmo conversacional. Si no puedes hablar, baja el ritmo.',1,null,900,0,7.0),
('run_tempo','Carrera tempo','cardio','{full_body}','ninguno',2,'Corre a ritmo exigente pero sostenible durante el tiempo indicado.',1,null,1200,0,9.8),
('sprint_intervals','Sprints por intervalos','cardio','{piernas,full_body}','ninguno',3,'Sprint máximo 20 segundos, camina 60. Repite las rondas indicadas.',8,null,20,60,12.0),
('jump_rope','Cuerda (saltar)','cardio','{full_body}','ninguno',2,'Salta la cuerda a ritmo constante. Descansa cuando pierdas el ritmo y retoma.',3,null,120,60,11.0),
('jumping_jacks','Jumping jacks','cardio','{full_body}','ninguno',1,'Salta abriendo piernas y brazos a la vez, regresa y repite a buen ritmo.',3,null,45,30,8.0),
('high_knees','Rodillas al pecho','cardio','{piernas,core}','ninguno',2,'Corre en tu lugar subiendo las rodillas a la altura de la cadera, rápido.',3,null,30,30,9.0),
('burpees','Burpees','cardio','{full_body}','ninguno',3,'Sentadilla, plancha, lagartija, salto. La misión más temida del Sistema.',3,10,null,60,10.0),
('box_jump','Saltos al cajón','cardio','{piernas,gluteos}','ninguno',3,'Salta con ambos pies a un cajón o banco firme. Baja con cuidado, no de salto.',3,8,null,75,8.0),
('skater_jumps','Saltos de patinador','cardio','{piernas,gluteos}','ninguno',2,'Salta lateralmente de una pierna a otra como patinador de velocidad.',3,null,30,45,8.5),
('shadow_boxing','Boxeo de sombra','cardio','{brazos,core,full_body}','ninguno',1,'Lanza combinaciones de golpes al aire moviéndote ligero. Como Yuki cazando.',3,null,120,60,7.8),
('stairs','Subir escaleras','cardio','{piernas,gluteos}','ninguno',2,'Sube y baja escaleras a ritmo constante. Usa el barandal solo si lo necesitas.',1,null,600,0,8.8),
('cycling','Bicicleta','cardio','{piernas}','maquina',1,'Pedalea a ritmo moderado. Resistencia media, cadencia constante.',1,null,1200,0,7.5),
('rowing_machine','Remo en máquina','cardio','{espalda,piernas,full_body}','maquina',2,'Empuja con piernas, luego jala con espalda y brazos. Ritmo fluido.',1,null,900,0,8.5),
('walk_brisk','Caminata rápida','cardio','{full_body}','ninguno',1,'Camina a paso acelerado, brazos activos. Ideal para días de recuperación.',1,null,1800,0,4.3),
('hiit_circuit','Circuito HIIT','cardio','{full_body}','ninguno',3,'40 segundos de trabajo máximo, 20 de descanso. Encadena los ejercicios del circuito.',6,null,40,20,11.0),
('bear_crawl','Caminata de oso','cardio','{full_body,core}','ninguno',2,'A cuatro puntos con rodillas elevadas, avanza coordinando mano y pie contrarios.',3,null,30,45,7.0),

-- ===== FLEXIBILIDAD / MOVILIDAD =====
('cat_cow','Gato-vaca','flexibility','{espalda,core}','ninguno',1,'A cuatro puntos, alterna arquear y redondear la espalda lento, respirando profundo.',2,10,null,30,2.5),
('downward_dog','Perro boca abajo','flexibility','{espalda,piernas,hombros}','ninguno',1,'Desde plancha, eleva la cadera formando una V invertida. Talones buscan el suelo.',3,null,30,30,2.5),
('cobra_stretch','Cobra','flexibility','{core,espalda}','ninguno',1,'Boca abajo, empuja con las manos elevando el pecho. Cadera en el suelo.',3,null,25,30,2.5),
('childs_pose','Postura del niño','flexibility','{espalda,hombros}','ninguno',1,'Rodillas al suelo, siéntate sobre talones y estira los brazos al frente. Relaja.',2,null,40,30,2.0),
('pigeon_pose','Postura de la paloma','flexibility','{gluteos,piernas}','ninguno',2,'Una pierna doblada al frente, la otra extendida atrás. Inclínate sobre la delantera.',2,null,40,30,2.5),
('hamstring_stretch','Estiramiento de isquios','flexibility','{piernas}','ninguno',1,'Sentado, una pierna extendida. Inclínate hacia el pie con espalda larga.',2,null,30,30,2.0),
('quad_stretch','Estiramiento de cuádriceps','flexibility','{piernas}','ninguno',1,'De pie, lleva el talón al glúteo sujetando el empeine. Rodillas juntas.',2,null,30,30,2.0),
('hip_flexor_stretch','Estiramiento de psoas','flexibility','{piernas,gluteos}','ninguno',1,'Rodilla en el suelo en posición de desplante. Empuja la cadera al frente.',2,null,30,30,2.0),
('butterfly_stretch','Mariposa','flexibility','{piernas,gluteos}','ninguno',1,'Sentado, plantas de los pies juntas. Acerca los talones y baja las rodillas suave.',2,null,40,30,2.0),
('shoulder_stretch','Estiramiento de hombros','flexibility','{hombros,brazos}','ninguno',1,'Cruza un brazo frente al pecho y presiona suave con el otro. Cambia de lado.',2,null,25,30,2.0),
('thoracic_rotation','Rotación torácica','flexibility','{espalda,core}','ninguno',2,'A cuatro puntos, mano en la nuca. Gira el torso abriendo el codo al cielo.',2,10,null,30,2.5),
('worlds_greatest','El mejor estiramiento del mundo','flexibility','{full_body}','ninguno',2,'Desplante profundo, mano al suelo, gira el torso abriendo el brazo al cielo. Alterna.',2,8,null,45,3.0),
('deep_squat_hold','Sentadilla profunda sostenida','flexibility','{piernas,gluteos}','ninguno',2,'Baja a sentadilla profunda y quédate ahí, talones en el suelo, codos empujando rodillas.',3,null,40,45,2.5),
('bridge_pose','Puente de yoga','flexibility','{espalda,gluteos}','ninguno',2,'Acostado, eleva la cadera y entrelaza las manos bajo el cuerpo. Abre el pecho.',3,null,30,30,2.5),
('neck_rolls','Movilidad de cuello','flexibility','{hombros}','ninguno',1,'Gira la cabeza en círculos lentos, ambas direcciones. Sin forzar.',2,8,null,20,1.5),
('ankle_mobility','Movilidad de tobillo','flexibility','{piernas}','ninguno',1,'En desplante corto, lleva la rodilla sobre el pie sin despegar el talón.',2,12,null,30,2.0),
('wrist_mobility','Movilidad de muñecas','flexibility','{brazos}','ninguno',1,'Círculos y estiramientos de muñeca en ambas direcciones. Clave antes de calistenia.',2,10,null,20,1.5),
('side_bend','Flexión lateral','flexibility','{core}','ninguno',1,'De pie, brazo sobre la cabeza, inclínate al lado contrario estirando el costado.',2,null,25,30,2.0),
('frog_stretch','Estiramiento de rana','flexibility','{piernas,gluteos}','ninguno',3,'A cuatro puntos, rodillas muy abiertas. Empuja la cadera atrás suave. Intenso.',2,null,40,45,2.5),
('couch_stretch','Estiramiento de sofá','flexibility','{piernas}','ninguno',3,'Pie trasero elevado contra pared o sofá en desplante. Tronco erguido. Avanzado.',2,null,40,45,2.5);
